export const siteInfo: any = {
  siteMap: {
    "https://sellercentral.amazon.com": "US",
    "https://sellercentral-japan.amazon.com": "JP",
    "https://sellercentral.amazon.ca": "US",
    "https://sellercentral.amazon.de": "UK",
    "https://sellercentral.amazon.com.au": "AU",
    "https://sellercentral-europe.amazon.com": "UK",
    "https://sellercentral.amazon.in": "IN",
    "https://sellercentral.amazon.ae": "AE",
    "https://sellercentral.amazon.co.uk": "UK",
    "https://sellercentral.amazon.sg": "SG",
    "https://sellercentral.amazon.fr": "UK",
    "https://sellercentral.amazon.it": "UK",
    "https://sellercentral.amazon.es": "UK",
    "https://sellercentral.amazon.nl": "UK",
    "https://sellercentral.amazon.com.mx": "US",
    "https://sellercentral.amazon.com.br": "US",
    "https://sellercentral.amazon.se": "UK",
    "https://sellercentral.amazon.co.jp": "JP",
    "https://sellercentral.amazon.sa": "SA",
    "https://sellercentral.amazon.pl": "PL"
  },
  siteToUrlMap: {
    US: [
      "https://sellercentral.amazon.ca",
      "https://sellercentral.amazon.com",
      "https://sellercentral.amazon.com.mx",
      "https://sellercentral.amazon.com.br"
    ],
    UK: [
      "https://sellercentral.amazon.de",
      "https://sellercentral-europe.amazon.com",
      "https://sellercentral.amazon.co.uk",
      "https://sellercentral.amazon.fr",
      "https://sellercentral.amazon.it",
      "https://sellercentral.amazon.es",
      "https://sellercentral.amazon.nl",
      "https://sellercentral.amazon.pl",
      "https://sellercentral.amazon.se"
    ],
    JP: [
      "https://sellercentral-japan.amazon.com",
      "https://sellercentral.amazon.co.jp"
    ],
    AU: ["https://sellercentral.amazon.com.au"],
    IN: ["https://sellercentral.amazon.in"],
    AE: ["https://sellercentral.amazon.ae"],
    SG: ["https://sellercentral.amazon.sg"],
    SA: ["https://sellercentral.amazon.sa"]
  },
  siteToLang: {
    US: "en_US",
    UK: "en_GB",
    JP: "en_US",
    AU: "en_US",
    IN: "en_US",
    AE: "en_US",
    SG: "en_US",
    SA: "en_US"
  },
  siteToMarketplaceMap: {
    "A2Q3Y263D00KWC": "US",
    "A2EUQ1WTGCTBG2": "US",
    "A1AM78C64UM0Y8": "US",
    "ATVPDKIKX0DER": "US",
    "A2VIGQ35RCS4UG": "AE",
    "A1PA6795UKMFR9": "UK",
    "ARBP9OOSHTCHU": "UK",
    "A1RKKUPIHCS9HS": "UK",
    "A13V1IB3VIYZZH": "UK",
    "A1F83G8C2ARO7P": "UK",
    "A21TJRUUN4KGV": "UK",
    "APJ6JRA9NG5V4": "UK",
    "A1805IZSGTT6HS": "UK",
    "A1C3SOZRARQ6R3": "UK",
    "A17E79C6D8DWNP": "SA",
    "A2NODRKZP88ZB9": "UK",
    "A33AVAJ2PDY3EV": "UK",
    "A19VAU5U5O7RUS": "JP",
    "A39IBJ37TRP1C6": "AU",
    "A1VC38T7YXB528": "JP"
  },
  MarketplaceLang: {
    US: "en_US",
    CA: "en_CA",
    BR: "en_BR",
    DE: "en_DE",
    FR: "en_FR",
    ES: "en_ES",
    IT: "en_IT",
    UK: "en_GB",
    PL: "en_GB",
    Other: "en_US",
    MX: "en_US",
    AE: "en_US",
    EG: "en_US",
    GB: "en_US",
    IN: "en_US",
    NL: "en_GB",
    SA: "en_US",
    TR: "en_US",
    SG: "en_US",
    AU: "en_US",
    JP: "en_JP",
    SE: "en_GB"
  },
  MarketplaceObj: {
    BR: "A2Q3Y263D00KWC",
    CA: "A2EUQ1WTGCTBG2",
    MX: "A1AM78C64UM0Y8",
    US: "ATVPDKIKX0DER",
    AE: "A2VIGQ35RCS4UG",
    DE: "A1PA6795UKMFR9",
    EG: "ARBP9OOSHTCHU",
    ES: "A1RKKUPIHCS9HS",
    FR: "A13V1IB3VIYZZH",
    UK: "A1F83G8C2ARO7P",
    GB: "A1F83G8C2ARO7P",
    IN: "A21TJRUUN4KGV",
    IT: "APJ6JRA9NG5V4",
    NL: "A1805IZSGTT6HS",
    SA: "A17E79C6D8DWNP",
    TR: "A33AVAJ2PDY3EV",
    SG: "A19VAU5U5O7RUS",
    AU: "A39IBJ37TRP1C6",
    JP: "A1VC38T7YXB528",
    SE: "A2NODRKZP88ZB9",
    PL: "A1C3SOZRARQ6R3"
  },
  codeToSiteMap: {
    A2Q3Y263D00KWC: "BR",
    A2EUQ1WTGCTBG2: "CA",
    A1AM78C64UM0Y8: "MX",
    ATVPDKIKX0DER: "US",
    A2VIGQ35RCS4UG: "AE",
    A1PA6795UKMFR9: "DE",
    ARBP9OOSHTCHU: "EG",
    A1RKKUPIHCS9HS: "ES",
    A13V1IB3VIYZZH: "FR",
    A1F83G8C2ARO7P: "UK",
    A21TJRUUN4KGV: "IN",
    APJ6JRA9NG5V4: "IT",
    A1805IZSGTT6HS: "NL",
    A17E79C6D8DWNP: "SA",
    A33AVAJ2PDY3EV: "TR",
    A19VAU5U5O7RUS: "SG",
    A39IBJ37TRP1C6: "AU",
    A1VC38T7YXB528: "JP",
    A2NODRKZP88ZB9: "SE",
    A1C3SOZRARQ6R3: "PL"
  },
  codeToCountryId: {
    US: 1,
    CA: 2,
    MX: 3,
    UK: 4,
    DE: 5,
    FR: 6,
    IT: 7,
    ES: 8,
    IN: 9,
    JP: 10,
    AU: 12,
    AE: 13,
    SG: 14,
    NL: 15,
    SA: 16,
    BR: 17,
    SE: 18
  }
}
export default siteInfo